In [1]:
# PROJECT AIM:
# lists of 5 most popular baby names in 2014 in US... 
# according to the statistical records on the CSV file?
import pandas as pd

In [2]:
us_baby_names = pd.read_csv('012 us_baby_names.csv')
us_baby_names

              Id       Name  Year Gender  Count
0              1       Mary  1880      F   7065
1              2       Anna  1880      F   2604
2              3       Emma  1880      F   2003
3              4  Elizabeth  1880      F   1939
4              5     Minnie  1880      F   1746
...          ...        ...   ...    ...    ...
1825428  1825429     Zykeem  2014      M      5
1825429  1825430     Zymeer  2014      M      5
1825430  1825431    Zymiere  2014      M      5
1825431  1825432      Zyran  2014      M      5
1825432  1825433      Zyrin  2014      M      5

[1825433 rows x 5 columns]

In [3]:
us_baby_names2014 = us_baby_names.loc[us_baby_names['Year'] == 2014, :]
us_baby_names2014

              Id      Name  Year Gender  Count
1792389  1792390      Emma  2014      F  20799
1792390  1792391    Olivia  2014      F  19674
1792391  1792392    Sophia  2014      F  18490
1792392  1792393  Isabella  2014      F  16950
1792393  1792394       Ava  2014      F  15586
...          ...       ...   ...    ...    ...
1825428  1825429    Zykeem  2014      M      5
1825429  1825430    Zymeer  2014      M      5
1825430  1825431   Zymiere  2014      M      5
1825431  1825432     Zyran  2014      M      5
1825432  1825433     Zyrin  2014      M      5

[33044 rows x 5 columns]

In [4]:
sorted_us_baby_names2014 = us_baby_names2014.sort_values('Count', ascending=True)
sorted_us_baby_names2014

              Id    Name  Year Gender  Count
1825415  1825416   Ziden  2014      M      5
1825416  1825417  Zierre  2014      M      5
1825417  1825418   Ziion  2014      M      5
1825418  1825419   Zijun  2014      M      5
1825419  1825420   Zilas  2014      M      5
...          ...     ...   ...    ...    ...
1811457  1811458    Liam  2014      M  18342
1792391  1792392  Sophia  2014      F  18490
1811456  1811457    Noah  2014      M  19144
1792390  1792391  Olivia  2014      F  19674
1792389  1792390    Emma  2014      F  20799

[33044 rows x 5 columns]

In [5]:
#These were the list of five USA babys' names that are not popular in the year 2014
five_most_uncommon_us_baby_names2014 = sorted_us_baby_names2014.iloc[0:5]
five_most_uncommon_us_baby_names2014

              Id    Name  Year Gender  Count
1825415  1825416   Ziden  2014      M      5
1825416  1825417  Zierre  2014      M      5
1825417  1825418   Ziion  2014      M      5
1825418  1825419   Zijun  2014      M      5
1825419  1825420   Zilas  2014      M      5